name: CI - Continuous Integration

on: ['push', 'pull_request']

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "$DATABASE_DRIVER://$DATABASE_USER:$DATABASE_PASS@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME"
      DATABASE_DRIVER: mysql
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: password
      DATABASE_NAME: stud_io_test
      HTTP_HOST: localhost
      HTTP_PORT: 3333
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      JWT_SECRET: 795e3633541d6a898b8e1f135b916e17
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}

    services:
      redis:
        image: redis:7.2-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: $DATABASE_PASS

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Set .env.test variables
        run: |
          echo DATABASE_URL=$DATABASE_URL >> .env.test
          echo DATABASE_DRIVER=$DATABASE_DRIVER >> .env.test
          echo DATABASE_HOST=$DATABASE_HOST >> .env.test
          echo DATABASE_PORT=$DATABASE_PORT >> .env.test
          echo DATABASE_USER=$DATABASE_USER >> .env.test
          echo DATABASE_PASS=$DATABASE_PASS >> .env.test
          echo DATABASE_PASS=$DATABASE_PASS >> .env.test
          echo JWT_SECRET=$JWT_SECRET >> .env.test
          echo SMTP_HOST=sandbox.smtp.mailtrap.io >> .env.test
          echo SMTP_PORT=2525 >> .env.test
          echo SMTP_USER=$SMTP_USER >> .env
          echo SMTP_PASS=$SMTP_PASS >> .env
          echo HTTP_HOST=HTTP_HOST >> .env
          echo HTTP_PORT=HTTP_PORT >> .env
          echo REDIS_HOST=REDIS_HOST >> .env
          echo REDIS_PORT=REDIS_PORT >> .env

      - name: Run e2e tests
        run: npm run test:e2e
